ros_impedance_controller:
  type: ros_impedance_controller/Controller
  joints:
    - lf_bs_joint
    - rf_bs_joint
    - lh_bs_joint
    - rh_bs_joint


  gains:
      lf_bs_joint: {p: 5.0, i: 0.0, d: 0.1}
      rf_bs_joint: {p: 5.0, i: 0.0, d: 0.1}
      lh_bs_joint: {p: 5.0, i: 0.0, d: 0.1}
      rh_bs_joint: {p: 5.0, i: 0.0, d: 0.1}
    
  home:
      lf_bs_joint: 0.0
      rf_bs_joint: 0.0
      lh_bs_joint: 0.0
      rh_bs_joint: 0.0
    
